### ISSUE TITLE
output data folder is not created during neuron simulation (if not exist)

### ISSUE THREAD

**Issue by PALMS-gui** [wmglab-duke/ascent#10]
When running _submit.py_ on external (Azure) cluster, I first copy the "submit" folder to the cloud. In such case **empty** _nsims>>**>>data>>output_ folders are not copied. This causes the process to crash later when attempting to write output files, because this folder is not found and not recreated.

As a workaround I have to create an empty .txt file in each output folder before copying to the cloud.

Would be better if the folder is created during the run-time (in case not existing)

**Comment by dmarshall-bing** [comment]
Hi! This issue will be fixed in the next release. For now, can you try changing line 477 in src/neuron/submit.py from

`for cur_dir in [out_dir, err_dir]:`
                
`for cur_dir in [fibers_path, output_path, out_dir, err_dir]:`

and then regenerate your output folder. This should fix the problem.

**Comment by ericmusselman** [comment]
This is fixed in v1.1.1, released Jan 27, 2022
