### ISSUE TITLE
some of the default\template JSON parameters aren't the best choice for beginners

### ISSUE THREAD

**Issue by PALMS-gui** [wmglab-duke/ascent#11]
Some parameter values in json templates aren't the best choice for new users:

1) "dt": 0.001  in sims>>waveform: generates data at 1 MHz resulting in unnecessary huge files
2) "n_min_aps": 1 in sims>>threshold: is not enough to generate multiple action potentials in time (see https://github.com/wmglab-duke/ascent/discussions/8)

**Comment by dmarshall-bing** [comment]
This would be something better placed in discussion if there isn't an error or deficiency in the code.
For our purposes (including the beta task) we are generally modeling short timescale data (fiber block and activation), so the 1st parameter hasn't been a problem. 
For n_min_aps we generally want activation searches to stop once they have detected an action potential (i.e. axonal activation). Setting n_min_aps to not equal one generally represents a more specialized use case.
Thanks for the feedback!
