### ISSUE TITLE
Issue running C fiber simulations

### ISSUE THREAD

**Issue by eliefarah19** [wmglab-duke/ascent#27]
I am getting the following error when I try to submit simulations that use C fiber types. The exact same error message is displayed when trying to run both SUNDT and TIGERHOLM models. I have no issue running the pipeline or submitting data for the beta task, which is not a C fiber. I'm using the same model and sample as the beta task, but I'm switching the sim and run configs to work for these other fiber models. 

start_scripts/0_0_start.sh: line 2: cd: n_sims/0_0_1_0: No such file or directory
/Library/Frameworks/Python.framework/Versions/3.9/bin/nrniv: not a Python nrn.Section
 in Wrapper.hoc near line 60
 ^
        SectionList[0].append(SectionRef[0])
      cFiberBuilder[0].build()
    cFiberBuilder[0].init(0.8, 12507.8, 2, 37, 8.333, 0, 0, 0)
  CreateAxon_CFiber()
and others

**Comment by eliefarah19** [comment]
Definitely. I'm getting it in all of the err logs for the n_sim/0_0_1_0/logs/err folder

**Comment by dmarshall-bing** [comment]
Does this include this line? 
`start_scripts/0_0_start.sh: line 2: cd: n_sims/0_0_1_0: No such file or directory
`

**Comment by eliefarah19** [comment]
Yes, they both are output to the same error log. n_sims/0_0_1_0 exists as a directory in submit/. 

Additionally, and I'm only noting this just now, the same line appears in my error logs for the beta task. That being said, I can successfully compile and run the beta task normally, and I output the expected values despite this error message.
