### ISSUE TITLE
Low activation threshold values from example experiments

### ISSUE THREAD

**Issue by PALMS-gui** [wmglab-duke/ascent#6]
Simulation using example files from bucksot_2019 leads to very low activation threshold values ~ 0.0x mA, although I use all json files from the repository. I get similar range values for my custom experiments as well, when I expect them to be ~10-20 times higher.
What can I possibly be doing wrong?

**Comment by ericmusselman** [comment]
Do the values disagree with the thresholds plotted in Fig 5A? I think it is possible you are getting the same results we did. Our replication of the Bucksot et al., 2019 model yields some threshold values in the 0.0x mA range for the largest fiber diameters (see ~10-16 um diameter fibers which are green -> yellow).

**Comment by PALMS-gui** [comment]
Thanks for your reply. I didn't expect such low thresholds as I am trying to reproduce another paper (where they use 8.7 micrometer fibers and 5.4 mA stimulation current) in my custom ASCENT simulation. Obviously many other conditions (media, cuff config) are not the same and this will affect the results. At least, I now know that my ASCENT setup is working.
