### ISSUE TITLE
Interpreting fiber's response during the ACTIVATION_THRESHOLD protocol

### ISSUE THREAD

**Issue by PALMS-gui** [wmglab-duke/ascent#9]
### Discussed in https://github.com/wmglab-duke/ascent/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **PALMS-gui** November 29, 2021</sup>
I have done a simulation for ACTIVATION_THRESHOLD protocol and received _thresh_inner0_fiber0.dat_ file as well as _Vm_time_inner0_fiber0_amp0.dat_.
I assume that the second file represents the fiber response when given sample is stimulated by estimated threshold. 
Can you help me understand to which extent the protocol parameters may affect the response: 
```
 "threshold": {
      "value": Double,
      "n_min_aps": Integer,
      "ap_detect_location": Double
    }
```
Especially interested in the last one - at which location of the nerve to detect the AP? Is there a rule of thumb for this (e.g. the closest\furthest from the cuff electrodes?)

In my particular simulation I see the following Vm traces:
![afbeelding](https://user-images.githubusercontent.com/72300527/143905509-7b7281ea-6400-42d1-b5d6-6def2fed19e0.png)
that is 5 AP close by in the very beginning of the simulation and nothing afterwards, though stimulation is going on until 500 ms.

![afbeelding](https://user-images.githubusercontent.com/72300527/143907228-6eb0328e-aa35-4819-88f9-edef231aae1d.png)
How do I interpret this? 
Is the axons' refraction period so long (can't be, right?) or is it blocked? Trying to grasp the basics here, so thanks...

 

</div>

**Comment by dmarshall-bing** [comment]
Closing since answered in Discussion
